package org.jooq.impl;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import org.jooq.tools.jdbc.DefaultCallableStatement;

/* loaded from: server.jar:BOOT-INF/lib/jooq-3.19.3.jar:org/jooq/impl/DiagnosticsStatement.class */
final class DiagnosticsStatement extends DefaultCallableStatement {
    final DiagnosticsConnection connection;
    final String actualStatement;

    /* JADX INFO: Access modifiers changed from: package-private */
    public DiagnosticsStatement(DiagnosticsConnection connection, Statement statement) {
        this(connection, statement, null);
    }

    /* JADX INFO: Access modifiers changed from: package-private */
    public DiagnosticsStatement(DiagnosticsConnection connection, Statement statement, String actualStatement) {
        super(statement);
        this.connection = connection;
        this.actualStatement = actualStatement;
    }

    @Override // org.jooq.tools.jdbc.DefaultStatement, java.sql.Statement
    public final ResultSet executeQuery(String sql) throws SQLException {
        if (this.connection.disabled()) {
            return super.executeQuery(sql);
        }
        return new DiagnosticsResultSet(super.executeQuery(this.connection.parse(sql)), sql, this, this.connection);
    }

    @Override // org.jooq.tools.jdbc.DefaultPreparedStatement, java.sql.PreparedStatement
    public ResultSet executeQuery() throws SQLException {
        if (this.connection.disabled()) {
            return super.executeQuery();
        }
        return new DiagnosticsResultSet(super.executeQuery(), this.actualStatement, this, this.connection);
    }

    @Override // org.jooq.tools.jdbc.DefaultStatement, java.sql.Statement
    public final int executeUpdate(String sql) throws SQLException {
        return super.executeUpdate(this.connection.parse(sql));
    }

    @Override // org.jooq.tools.jdbc.DefaultStatement, java.sql.Statement
    public final int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        return super.executeUpdate(this.connection.parse(sql), autoGeneratedKeys);
    }

    @Override // org.jooq.tools.jdbc.DefaultStatement, java.sql.Statement
    public final int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        return super.executeUpdate(this.connection.parse(sql), columnIndexes);
    }

    @Override // org.jooq.tools.jdbc.DefaultStatement, java.sql.Statement
    public final int executeUpdate(String sql, String[] columnNames) throws SQLException {
        return super.executeUpdate(this.connection.parse(sql), columnNames);
    }

    @Override // org.jooq.tools.jdbc.DefaultStatement, java.sql.Statement
    public final boolean execute(String sql) throws SQLException {
        return super.execute(this.connection.parse(sql));
    }

    @Override // org.jooq.tools.jdbc.DefaultStatement, java.sql.Statement
    public final boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        return super.execute(this.connection.parse(sql), autoGeneratedKeys);
    }

    @Override // org.jooq.tools.jdbc.DefaultStatement, java.sql.Statement
    public final boolean execute(String sql, int[] columnIndexes) throws SQLException {
        return super.execute(this.connection.parse(sql), columnIndexes);
    }

    @Override // org.jooq.tools.jdbc.DefaultStatement, java.sql.Statement
    public final boolean execute(String sql, String[] columnNames) throws SQLException {
        return super.execute(this.connection.parse(sql), columnNames);
    }

    @Override // org.jooq.tools.jdbc.DefaultStatement
    public final long executeLargeUpdate(String sql) throws SQLException {
        return super.executeLargeUpdate(this.connection.parse(sql));
    }

    @Override // org.jooq.tools.jdbc.DefaultStatement
    public final long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        return super.executeLargeUpdate(this.connection.parse(sql), autoGeneratedKeys);
    }

    @Override // org.jooq.tools.jdbc.DefaultStatement
    public final long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException {
        return super.executeLargeUpdate(this.connection.parse(sql), columnIndexes);
    }

    @Override // org.jooq.tools.jdbc.DefaultStatement
    public final long executeLargeUpdate(String sql, String[] columnNames) throws SQLException {
        return super.executeLargeUpdate(this.connection.parse(sql), columnNames);
    }

    @Override // org.jooq.tools.jdbc.DefaultStatement, java.sql.Statement
    public final void addBatch(String sql) throws SQLException {
        super.addBatch(this.connection.parse(sql));
    }

    @Override // org.jooq.tools.jdbc.DefaultStatement, java.sql.Statement
    public final Connection getConnection() throws SQLException {
        return this.connection;
    }
}
