package org.jooq.impl;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Predicate;
import org.jooq.Configuration;
import org.jooq.Parser;
import org.jooq.Queries;
import org.jooq.RenderContext;
import org.jooq.conf.ParamType;
import org.jooq.conf.Settings;
import org.jooq.tools.jdbc.DefaultConnection;

/* loaded from: server.jar:BOOT-INF/lib/jooq-3.19.3.jar:org/jooq/impl/DiagnosticsConnection.class */
final class DiagnosticsConnection extends DefaultConnection {
    static final int LRU_SIZE_GLOBAL = 50000;
    static final int LRU_SIZE_LOCAL = 500;
    static final int DUP_SIZE = 500;
    final Map<String, List<String>> repeatedSQL;
    final Map<String, List<String>> consecutiveAgg;
    final Configuration configuration;
    final Configuration configurationTranformPatterns;
    final RenderContext normalisingRenderer;
    final Parser parser;
    final DiagnosticsListeners listeners;
    final boolean release;

    /* JADX INFO: Access modifiers changed from: package-private */
    public DiagnosticsConnection(Configuration configuration) {
        this(configuration, null);
    }

    /* JADX INFO: Access modifiers changed from: package-private */
    public DiagnosticsConnection(Configuration configuration, Connection c) {
        super(c != null ? c : configuration.connectionProvider().acquire());
        this.repeatedSQL = new LRU(500);
        this.consecutiveAgg = new LRU(500);
        this.release = c == null;
        this.configuration = configuration;
        this.configurationTranformPatterns = configuration.deriveSettings(s -> {
            return s.withTransformPatterns(true);
        });
        this.normalisingRenderer = configuration.deriveSettings(s2 -> {
            return s2.withParamType(ParamType.FORCE_INDEXED).withInListPadding(true).withInListPadBase(16);
        }).dsl().renderContext();
        this.parser = configuration.dsl().parser();
        this.listeners = DiagnosticsListeners.get(configuration);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public final Statement createStatement() throws SQLException {
        return new DiagnosticsStatement(this, getDelegate().createStatement());
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public final Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
        return new DiagnosticsStatement(this, getDelegate().createStatement(resultSetType, resultSetConcurrency));
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public final Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return new DiagnosticsStatement(this, getDelegate().createStatement(resultSetType, resultSetConcurrency, resultSetHoldability));
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public final PreparedStatement prepareStatement(String sql) throws SQLException {
        return new DiagnosticsStatement(this, getDelegate().prepareStatement(parse(sql)), sql);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public final PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        return new DiagnosticsStatement(this, getDelegate().prepareStatement(parse(sql), resultSetType, resultSetConcurrency), sql);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public final PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return new DiagnosticsStatement(this, getDelegate().prepareStatement(parse(sql), resultSetType, resultSetConcurrency, resultSetHoldability), sql);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public final PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return new DiagnosticsStatement(this, getDelegate().prepareStatement(parse(sql), autoGeneratedKeys), sql);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public final PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        return new DiagnosticsStatement(this, getDelegate().prepareStatement(parse(sql), columnIndexes), sql);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public final PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        return new DiagnosticsStatement(this, getDelegate().prepareStatement(parse(sql), columnNames), sql);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public final CallableStatement prepareCall(String sql) throws SQLException {
        return new DiagnosticsStatement(this, getDelegate().prepareCall(parse(sql)), sql);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public final CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        return new DiagnosticsStatement(this, getDelegate().prepareCall(parse(sql), resultSetType, resultSetConcurrency), sql);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public final CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return new DiagnosticsStatement(this, getDelegate().prepareCall(parse(sql), resultSetType, resultSetConcurrency, resultSetHoldability), sql);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection, java.lang.AutoCloseable
    public final void close() throws SQLException {
        this.repeatedSQL.clear();
        if (this.release) {
            this.configuration.connectionProvider().release(getDelegate());
        }
    }

    final boolean checkPattern(Predicate<? super Settings> test) {
        return DiagnosticsListeners.checkPattern(this.configuration.settings(), test);
    }

    /* JADX INFO: Access modifiers changed from: package-private */
    public final boolean check(Predicate<? super Settings> test) {
        return DiagnosticsListeners.check(this.configuration.settings(), test);
    }

    final Map<String, Set<String>> duplicateSql() {
        return (Map) this.configuration.data().computeIfAbsent("org.jooq.diagnostics.duplicate-sql", k -> {
            return Collections.synchronizedMap(new LRU(LRU_SIZE_GLOBAL));
        });
    }

    /* JADX INFO: Access modifiers changed from: package-private */
    public final boolean disabled() {
        return this.configuration.settings().getDiagnosticsConnection() == org.jooq.conf.DiagnosticsConnection.OFF;
    }

    /* JADX INFO: Access modifiers changed from: package-private */
    public final String parse(String sql) {
        String normalised;
        List<String> repetitions;
        Set<String> duplicates;
        if (disabled()) {
            return sql;
        }
        Queries queries = null;
        Queries transformed = null;
        try {
            Queries parse = this.parser.parse(sql);
            queries = parse;
            transformed = parse;
            normalised = this.normalisingRenderer.render(transformed);
        } catch (ParserException exception) {
            normalised = sql;
            this.listeners.exception(new DefaultDiagnosticsContext(this.configuration, "Query could not be parsed.", sql, exception));
        }
        try {
            if (check((v0) -> {
                return v0.isDiagnosticsDuplicateStatements();
            }) && (duplicates = duplicates(duplicateSql(), sql, normalised)) != null) {
                this.listeners.duplicateStatements(new DefaultDiagnosticsContext(this.configuration, "Duplicate statements encountered.", sql, normalised, duplicates, null, queries, transformed, null));
            }
            if (check((v0) -> {
                return v0.isDiagnosticsRepeatedStatements();
            }) && (repetitions = repetitions(this.repeatedSQL, sql, normalised)) != null) {
                this.listeners.repeatedStatements(new DefaultDiagnosticsContext(this.configuration, "Repeated statements encountered.", sql, normalised, null, repetitions, queries, transformed, null));
            }
            if (queries != null) {
            }
        } catch (Error e) {
            throw e;
        } catch (Throwable exception2) {
            this.listeners.exception(new DefaultDiagnosticsContext(this.configuration, "An unexpected exception has occurred. See exception for details.", sql, normalised, null, null, queries, transformed, exception2));
        }
        return sql;
    }

    private final Set<String> duplicates(Map<String, Set<String>> map, String sql, String normalised) {
        synchronized (map) {
            Set<String> v = map.computeIfAbsent(normalised, k -> {
                return new HashSet();
            });
            if (v.size() >= 500 || (v.add(sql) && v.size() > 1)) {
                return v;
            }
            return null;
        }
    }

    private final List<String> repetitions(Map<String, List<String>> map, String sql, String normalised) {
        List<String> v = map.computeIfAbsent(normalised, k -> {
            return new ArrayList();
        });
        if (v.size() >= 500 || (v.add(sql) && v.size() > 1)) {
            return v;
        }
        return null;
    }

    /* JADX INFO: Access modifiers changed from: package-private */
    /* loaded from: server.jar:BOOT-INF/lib/jooq-3.19.3.jar:org/jooq/impl/DiagnosticsConnection$LRU.class */
    public static final class LRU<V> extends LinkedHashMap<String, V> {
        private final int size;

        LRU(int size) {
            super(size + 1, 1.0f, true);
            this.size = size;
        }

        @Override // java.util.LinkedHashMap
        protected boolean removeEldestEntry(Map.Entry<String, V> eldest) {
            return size() > this.size;
        }
    }
}
