package org.jooq.impl;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import org.jooq.ExecuteContext;
import org.jooq.conf.Settings;
import org.jooq.conf.SettingsTools;
import org.jooq.impl.Tools;
import org.jooq.tools.jdbc.DefaultConnection;

/* JADX INFO: Access modifiers changed from: package-private */
/* loaded from: server.jar:BOOT-INF/lib/jooq-3.19.3.jar:org/jooq/impl/SettingsEnabledConnection.class */
public final class SettingsEnabledConnection extends DefaultConnection {
    private final Settings settings;
    private final ExecuteContext ctx;

    /* JADX INFO: Access modifiers changed from: package-private */
    public SettingsEnabledConnection(Connection delegate, Settings settings, ExecuteContext ctx) {
        super(delegate);
        this.settings = settings;
        this.ctx = ctx;
    }

    private final boolean executePreparedStatements0() {
        return SettingsTools.executePreparedStatements(this.settings) && !Boolean.TRUE.equals(this.ctx.data(Tools.BooleanDataKey.DATA_FORCE_STATIC_STATEMENT));
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public final PreparedStatement prepareStatement(String sql) throws SQLException {
        if (executePreparedStatements0()) {
            return getDelegate().prepareStatement(sql);
        }
        return new SettingsEnabledPreparedStatement(getDelegate(), sql);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public final PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        if (executePreparedStatements0()) {
            return getDelegate().prepareStatement(sql, resultSetType, resultSetConcurrency);
        }
        return new SettingsEnabledPreparedStatement(getDelegate(), sql, resultSetType, resultSetConcurrency);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public final PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        if (executePreparedStatements0()) {
            return getDelegate().prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
        }
        return new SettingsEnabledPreparedStatement(getDelegate(), sql, resultSetType, resultSetConcurrency, resultSetHoldability);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public final PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        if (executePreparedStatements0()) {
            return getDelegate().prepareStatement(sql, autoGeneratedKeys);
        }
        return new SettingsEnabledPreparedStatement(getDelegate(), sql, autoGeneratedKeys);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public final PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        if (executePreparedStatements0()) {
            return getDelegate().prepareStatement(sql, columnIndexes);
        }
        return new SettingsEnabledPreparedStatement(getDelegate(), sql, columnIndexes);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public final PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        if (executePreparedStatements0()) {
            return getDelegate().prepareStatement(sql, columnNames);
        }
        return new SettingsEnabledPreparedStatement(getDelegate(), sql, columnNames);
    }
}
