package org.jooq.tools.jdbc;

import java.sql.CallableStatement;
import java.sql.ClientInfoStatus;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Savepoint;
import java.sql.Statement;
import java.util.Collections;
import java.util.Map;
import java.util.Properties;
import java.util.regex.Pattern;

/* loaded from: server.jar:BOOT-INF/lib/jooq-3.19.3.jar:org/jooq/tools/jdbc/BatchedConnection.class */
public class BatchedConnection extends DefaultConnection {
    final int batchSize;
    String lastSQL;
    BatchedPreparedStatement lastStatement;
    static final Pattern P_DML = Pattern.compile("\\s*(?i:delete|insert|merge|update).*");

    public BatchedConnection(Connection delegate) {
        this(delegate, Integer.MAX_VALUE);
    }

    public BatchedConnection(Connection delegate, int batchSize) {
        super(delegate);
        this.batchSize = batchSize;
    }

    /* JADX WARN: Multi-variable type inference failed */
    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Wrapper
    public <T> T unwrap(Class<T> cls) throws SQLException {
        return BatchedConnection.class == cls ? this : (T) super.unwrap(cls);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Wrapper
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        return BatchedConnection.class == iface || super.isWrapperFor(iface);
    }

    void executeLastBatch(String sql) throws SQLException {
        if (!sql.equals(this.lastSQL)) {
            executeLastBatch();
        }
    }

    /* JADX INFO: Access modifiers changed from: package-private */
    public void executeLastBatch() throws SQLException {
        if (this.lastStatement != null) {
            if (this.lastStatement.batches > 0) {
                this.lastStatement.executeBatch();
            }
            JDBCUtils.safeClose((Statement) this.lastStatement);
        }
        clearLastBatch();
    }

    void clearLastBatch() {
        this.lastStatement = null;
        this.lastSQL = null;
    }

    /* JADX INFO: Access modifiers changed from: package-private */
    public void setBatch(BatchedPreparedStatement s) throws SQLException {
        if (this.lastStatement == s) {
            return;
        }
        if (this.lastStatement != null) {
            executeLastBatch();
        }
        this.lastStatement = s;
        this.lastSQL = s.sql;
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public Statement createStatement() throws SQLException {
        executeLastBatch();
        return super.createStatement();
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
        executeLastBatch();
        return super.createStatement(resultSetType, resultSetConcurrency);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        executeLastBatch();
        return super.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        executeLastBatch();
        return super.prepareStatement(sql, resultSetType, resultSetConcurrency);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        executeLastBatch();
        return super.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        executeLastBatch();
        return super.prepareStatement(sql, autoGeneratedKeys);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        executeLastBatch();
        return super.prepareStatement(sql, columnIndexes);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        executeLastBatch();
        return super.prepareStatement(sql, columnNames);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public CallableStatement prepareCall(String sql) throws SQLException {
        executeLastBatch();
        return super.prepareCall(sql);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        executeLastBatch();
        return super.prepareCall(sql, resultSetType, resultSetConcurrency);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        executeLastBatch();
        return super.prepareCall(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        executeLastBatch(sql);
        return this.lastStatement != null ? this.lastStatement : prepareStatement0(sql);
    }

    private PreparedStatement prepareStatement0(String sql) throws SQLException {
        PreparedStatement result = super.prepareStatement(sql);
        if (P_DML.matcher(sql).matches()) {
            this.lastSQL = sql;
            BatchedPreparedStatement batchedPreparedStatement = new BatchedPreparedStatement(sql, this, result);
            this.lastStatement = batchedPreparedStatement;
            return batchedPreparedStatement;
        }
        return result;
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public void commit() throws SQLException {
        executeLastBatch();
        super.commit();
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public void rollback() throws SQLException {
        executeLastBatch();
        super.rollback();
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public void rollback(Savepoint savepoint) throws SQLException {
        executeLastBatch();
        super.rollback(savepoint);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection, java.lang.AutoCloseable
    public void close() throws SQLException {
        executeLastBatch();
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public Savepoint setSavepoint() throws SQLException {
        executeLastBatch();
        return super.setSavepoint();
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public Savepoint setSavepoint(String name) throws SQLException {
        executeLastBatch();
        return super.setSavepoint(name);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public void releaseSavepoint(Savepoint savepoint) throws SQLException {
        executeLastBatch();
        super.releaseSavepoint(savepoint);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public void setAutoCommit(boolean autoCommit) throws SQLException {
        executeLastBatch();
        super.setAutoCommit(autoCommit);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public boolean getAutoCommit() throws SQLException {
        executeLastBatch();
        return super.getAutoCommit();
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public void setReadOnly(boolean readOnly) throws SQLException {
        executeLastBatch();
        super.setReadOnly(readOnly);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public boolean isReadOnly() throws SQLException {
        executeLastBatch();
        return super.isReadOnly();
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public void setCatalog(String catalog) throws SQLException {
        executeLastBatch();
        super.setCatalog(catalog);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public String getCatalog() throws SQLException {
        executeLastBatch();
        return super.getCatalog();
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public SQLWarning getWarnings() throws SQLException {
        executeLastBatch();
        return super.getWarnings();
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public void clearWarnings() throws SQLException {
        executeLastBatch();
        super.clearWarnings();
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public void setTransactionIsolation(int level) throws SQLException {
        executeLastBatch();
        super.setTransactionIsolation(level);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public int getTransactionIsolation() throws SQLException {
        executeLastBatch();
        return super.getTransactionIsolation();
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public void setTypeMap(Map<String, Class<?>> map) throws SQLException {
        executeLastBatch();
        super.setTypeMap(map);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public Map<String, Class<?>> getTypeMap() throws SQLException {
        executeLastBatch();
        return super.getTypeMap();
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public void setHoldability(int holdability) throws SQLException {
        executeLastBatch();
        super.setHoldability(holdability);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public int getHoldability() throws SQLException {
        executeLastBatch();
        return super.getHoldability();
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public boolean isValid(int timeout) throws SQLException {
        executeLastBatch();
        return super.isValid(timeout);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public void setClientInfo(String name, String value) throws SQLClientInfoException {
        try {
            executeLastBatch();
            super.setClientInfo(name, value);
        } catch (SQLException e) {
            throw new SQLClientInfoException((Map<String, ClientInfoStatus>) Collections.emptyMap(), e);
        }
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public void setClientInfo(Properties properties) throws SQLClientInfoException {
        try {
            executeLastBatch();
            super.setClientInfo(properties);
        } catch (SQLException e) {
            throw new SQLClientInfoException((Map<String, ClientInfoStatus>) Collections.emptyMap(), e);
        }
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public String getClientInfo(String name) throws SQLException {
        executeLastBatch();
        return super.getClientInfo(name);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public Properties getClientInfo() throws SQLException {
        executeLastBatch();
        return super.getClientInfo();
    }
}
