package org.jooq.tools.jdbc;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;
import java.util.function.Supplier;

/* loaded from: server.jar:BOOT-INF/lib/jooq-3.19.3.jar:org/jooq/tools/jdbc/DefaultStatement.class */
public class DefaultStatement extends JDBC41Statement implements Statement {
    private final Statement delegate;
    private final Connection creator;
    private final Supplier<? extends SQLException> errorIfUnsupported;

    public DefaultStatement(Statement delegate) {
        this(delegate, null, null);
    }

    public DefaultStatement(Statement delegate, Connection creator) {
        this(delegate, creator, null);
    }

    public DefaultStatement(Statement delegate, Connection creator, Supplier<? extends SQLException> errorIfUnsupported) {
        this.delegate = delegate;
        this.creator = creator;
        this.errorIfUnsupported = errorIfUnsupported;
    }

    public Statement getDelegate() throws SQLException {
        return getDelegateStatement();
    }

    public Statement getDelegateStatement() throws SQLException {
        if (this.delegate != null || this.errorIfUnsupported == null) {
            return this.delegate;
        }
        throw this.errorIfUnsupported.get();
    }

    /* JADX INFO: Access modifiers changed from: protected */
    public ResultSet wrap(ResultSet wrapped) {
        if (wrapped == null) {
            return null;
        }
        return new DefaultResultSet(wrapped, this);
    }

    public boolean execute(String sql) throws SQLException {
        return getDelegateStatement().execute(sql);
    }

    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        return getDelegateStatement().execute(sql, autoGeneratedKeys);
    }

    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        return getDelegateStatement().execute(sql, columnIndexes);
    }

    public boolean execute(String sql, String[] columnNames) throws SQLException {
        return getDelegateStatement().execute(sql, columnNames);
    }

    public int[] executeBatch() throws SQLException {
        return getDelegateStatement().executeBatch();
    }

    public ResultSet executeQuery(String sql) throws SQLException {
        return wrap(getDelegateStatement().executeQuery(sql));
    }

    public int executeUpdate(String sql) throws SQLException {
        return getDelegateStatement().executeUpdate(sql);
    }

    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        return getDelegateStatement().executeUpdate(sql, autoGeneratedKeys);
    }

    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        return getDelegateStatement().executeUpdate(sql, columnIndexes);
    }

    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        return getDelegateStatement().executeUpdate(sql, columnNames);
    }

    public <T> T unwrap(Class<T> cls) throws SQLException {
        return (T) getDelegateStatement().unwrap(cls);
    }

    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        return getDelegateStatement().isWrapperFor(iface);
    }

    public void close() throws SQLException {
        getDelegateStatement().close();
    }

    @Override // java.sql.Statement
    public int getMaxFieldSize() throws SQLException {
        return getDelegateStatement().getMaxFieldSize();
    }

    @Override // java.sql.Statement
    public void setMaxFieldSize(int max) throws SQLException {
        getDelegateStatement().setMaxFieldSize(max);
    }

    @Override // java.sql.Statement
    public int getMaxRows() throws SQLException {
        return getDelegateStatement().getMaxRows();
    }

    @Override // java.sql.Statement
    public void setMaxRows(int max) throws SQLException {
        getDelegateStatement().setMaxRows(max);
    }

    @Override // java.sql.Statement
    public void setEscapeProcessing(boolean enable) throws SQLException {
        getDelegateStatement().setEscapeProcessing(enable);
    }

    @Override // java.sql.Statement
    public int getQueryTimeout() throws SQLException {
        return getDelegateStatement().getQueryTimeout();
    }

    @Override // java.sql.Statement
    public void setQueryTimeout(int seconds) throws SQLException {
        getDelegateStatement().setQueryTimeout(seconds);
    }

    @Override // java.sql.Statement
    public void cancel() throws SQLException {
        getDelegateStatement().cancel();
    }

    @Override // java.sql.Statement
    public SQLWarning getWarnings() throws SQLException {
        return getDelegateStatement().getWarnings();
    }

    @Override // java.sql.Statement
    public void clearWarnings() throws SQLException {
        getDelegateStatement().clearWarnings();
    }

    @Override // java.sql.Statement
    public void setCursorName(String name) throws SQLException {
        getDelegateStatement().setCursorName(name);
    }

    public ResultSet getResultSet() throws SQLException {
        return wrap(getDelegateStatement().getResultSet());
    }

    public int getUpdateCount() throws SQLException {
        return getDelegateStatement().getUpdateCount();
    }

    public boolean getMoreResults() throws SQLException {
        return getDelegateStatement().getMoreResults();
    }

    @Override // java.sql.Statement
    public void setFetchDirection(int direction) throws SQLException {
        getDelegateStatement().setFetchDirection(direction);
    }

    @Override // java.sql.Statement
    public int getFetchDirection() throws SQLException {
        return getDelegateStatement().getFetchDirection();
    }

    @Override // java.sql.Statement
    public void setFetchSize(int rows) throws SQLException {
        getDelegateStatement().setFetchSize(rows);
    }

    @Override // java.sql.Statement
    public int getFetchSize() throws SQLException {
        return getDelegateStatement().getFetchSize();
    }

    @Override // java.sql.Statement
    public int getResultSetConcurrency() throws SQLException {
        return getDelegateStatement().getResultSetConcurrency();
    }

    @Override // java.sql.Statement
    public int getResultSetType() throws SQLException {
        return getDelegateStatement().getResultSetType();
    }

    public void addBatch(String sql) throws SQLException {
        getDelegateStatement().addBatch(sql);
    }

    public void clearBatch() throws SQLException {
        getDelegateStatement().clearBatch();
    }

    public Connection getConnection() throws SQLException {
        return this.creator != null ? this.creator : getDelegateStatement().getConnection();
    }

    public boolean getMoreResults(int current) throws SQLException {
        return getDelegateStatement().getMoreResults(current);
    }

    public ResultSet getGeneratedKeys() throws SQLException {
        return wrap(getDelegateStatement().getGeneratedKeys());
    }

    @Override // java.sql.Statement
    public int getResultSetHoldability() throws SQLException {
        return getDelegateStatement().getResultSetHoldability();
    }

    @Override // java.sql.Statement
    public boolean isClosed() throws SQLException {
        return getDelegateStatement().isClosed();
    }

    @Override // java.sql.Statement
    public void setPoolable(boolean poolable) throws SQLException {
        getDelegateStatement().setPoolable(poolable);
    }

    @Override // java.sql.Statement
    public boolean isPoolable() throws SQLException {
        return getDelegateStatement().isPoolable();
    }

    @Override // org.jooq.tools.jdbc.JDBC41Statement
    public void closeOnCompletion() throws SQLException {
        getDelegate().closeOnCompletion();
    }

    @Override // org.jooq.tools.jdbc.JDBC41Statement
    public boolean isCloseOnCompletion() throws SQLException {
        return getDelegate().isCloseOnCompletion();
    }

    public long getLargeUpdateCount() throws SQLException {
        return getDelegate().getLargeUpdateCount();
    }

    public void setLargeMaxRows(long max) throws SQLException {
        getDelegate().setLargeMaxRows(max);
    }

    public long getLargeMaxRows() throws SQLException {
        return getDelegate().getLargeMaxRows();
    }

    public long[] executeLargeBatch() throws SQLException {
        return getDelegate().executeLargeBatch();
    }

    public long executeLargeUpdate(String sql) throws SQLException {
        return getDelegate().executeLargeUpdate(sql);
    }

    public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        return getDelegate().executeLargeUpdate(sql, autoGeneratedKeys);
    }

    public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException {
        return getDelegate().executeLargeUpdate(sql, columnIndexes);
    }

    public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException {
        return getDelegate().executeLargeUpdate(sql, columnNames);
    }

    public String enquoteLiteral(String val) throws SQLException {
        return getDelegate().enquoteLiteral(val);
    }

    public String enquoteIdentifier(String identifier, boolean alwaysQuote) throws SQLException {
        return getDelegate().enquoteIdentifier(identifier, alwaysQuote);
    }

    public boolean isSimpleIdentifier(String identifier) throws SQLException {
        return getDelegate().isSimpleIdentifier(identifier);
    }

    public String enquoteNCharLiteral(String val) throws SQLException {
        return getDelegate().enquoteNCharLiteral(val);
    }
}
