package org.jooq.tools.jdbc;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import org.jooq.tools.JooqLogger;

/* loaded from: server.jar:BOOT-INF/lib/jooq-3.19.3.jar:org/jooq/tools/jdbc/LoggingStatement.class */
public class LoggingStatement extends DefaultStatement {
    private static final JooqLogger log = JooqLogger.getLogger((Class<?>) LoggingStatement.class);

    public LoggingStatement(Statement delegate) {
        super(delegate);
    }

    @Override // org.jooq.tools.jdbc.DefaultStatement, java.sql.Statement
    public boolean execute(String sql) throws SQLException {
        if (log.isDebugEnabled()) {
            log.debug("execute", sql);
        }
        return super.execute(sql);
    }

    @Override // org.jooq.tools.jdbc.DefaultStatement, java.sql.Statement
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        if (log.isDebugEnabled()) {
            log.debug("execute", sql);
        }
        return super.execute(sql, autoGeneratedKeys);
    }

    @Override // org.jooq.tools.jdbc.DefaultStatement, java.sql.Statement
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        if (log.isDebugEnabled()) {
            log.debug("execute", sql);
        }
        return super.execute(sql, columnIndexes);
    }

    @Override // org.jooq.tools.jdbc.DefaultStatement, java.sql.Statement
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        if (log.isDebugEnabled()) {
            log.debug("execute", sql);
        }
        return super.execute(sql, columnNames);
    }

    @Override // org.jooq.tools.jdbc.DefaultStatement, java.sql.Statement
    public ResultSet executeQuery(String sql) throws SQLException {
        if (log.isDebugEnabled()) {
            log.debug("executeQuery", sql);
        }
        return super.executeQuery(sql);
    }

    @Override // org.jooq.tools.jdbc.DefaultStatement, java.sql.Statement
    public int executeUpdate(String sql) throws SQLException {
        if (log.isDebugEnabled()) {
            log.debug("executeUpdate", sql);
        }
        return super.executeUpdate(sql);
    }

    @Override // org.jooq.tools.jdbc.DefaultStatement, java.sql.Statement
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        if (log.isDebugEnabled()) {
            log.debug("executeUpdate", sql);
        }
        return super.executeUpdate(sql, autoGeneratedKeys);
    }

    @Override // org.jooq.tools.jdbc.DefaultStatement, java.sql.Statement
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        if (log.isDebugEnabled()) {
            log.debug("executeUpdate", sql);
        }
        return super.executeUpdate(sql, columnIndexes);
    }

    @Override // org.jooq.tools.jdbc.DefaultStatement, java.sql.Statement
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        if (log.isDebugEnabled()) {
            log.debug("executeUpdate", sql);
        }
        return super.executeUpdate(sql, columnNames);
    }

    @Override // org.jooq.tools.jdbc.DefaultStatement, java.sql.Statement
    public void addBatch(String sql) throws SQLException {
        if (log.isDebugEnabled()) {
            log.debug("addBatch", sql);
        }
        super.addBatch(sql);
    }

    @Override // org.jooq.tools.jdbc.DefaultStatement
    public long executeLargeUpdate(String sql) throws SQLException {
        if (log.isDebugEnabled()) {
            log.debug("executeLargeUpdate", sql);
        }
        return super.executeLargeUpdate(sql);
    }

    @Override // org.jooq.tools.jdbc.DefaultStatement
    public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        if (log.isDebugEnabled()) {
            log.debug("executeLargeUpdate", sql);
        }
        return super.executeLargeUpdate(sql, autoGeneratedKeys);
    }

    @Override // org.jooq.tools.jdbc.DefaultStatement
    public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException {
        if (log.isDebugEnabled()) {
            log.debug("executeLargeUpdate", sql);
        }
        return super.executeLargeUpdate(sql, columnIndexes);
    }

    @Override // org.jooq.tools.jdbc.DefaultStatement
    public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException {
        if (log.isDebugEnabled()) {
            log.debug("executeLargeUpdate", sql);
        }
        return super.executeLargeUpdate(sql, columnNames);
    }
}
