package org.jooq.tools.jdbc;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import org.jooq.tools.JooqLogger;

/* loaded from: server.jar:BOOT-INF/lib/jooq-3.19.3.jar:org/jooq/tools/jdbc/LoggingConnection.class */
public class LoggingConnection extends DefaultConnection {
    private static final JooqLogger log = JooqLogger.getLogger((Class<?>) LoggingConnection.class);

    public LoggingConnection(Connection delegate) {
        super(delegate);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public Statement createStatement() throws SQLException {
        return new LoggingStatement(super.createStatement());
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
        return new LoggingStatement(super.createStatement(resultSetType, resultSetConcurrency));
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return new LoggingStatement(super.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability));
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        if (log.isDebugEnabled()) {
            log.debug("prepareStatement", sql);
        }
        return super.prepareStatement(sql);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        if (log.isDebugEnabled()) {
            log.debug("prepareStatement", sql);
        }
        return super.prepareStatement(sql, resultSetType, resultSetConcurrency);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        if (log.isDebugEnabled()) {
            log.debug("prepareStatement", sql);
        }
        return super.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        if (log.isDebugEnabled()) {
            log.debug("prepareStatement", sql);
        }
        return super.prepareStatement(sql, autoGeneratedKeys);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        if (log.isDebugEnabled()) {
            log.debug("prepareStatement", sql);
        }
        return super.prepareStatement(sql, columnIndexes);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        if (log.isDebugEnabled()) {
            log.debug("prepareStatement", sql);
        }
        return super.prepareStatement(sql, columnNames);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public CallableStatement prepareCall(String sql) throws SQLException {
        if (log.isDebugEnabled()) {
            log.debug("prepareCall", sql);
        }
        return super.prepareCall(sql);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        if (log.isDebugEnabled()) {
            log.debug("prepareCall", sql);
        }
        return super.prepareCall(sql, resultSetType, resultSetConcurrency);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        if (log.isDebugEnabled()) {
            log.debug("prepareCall", sql);
        }
        return super.prepareCall(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
    }

    @Override // org.jooq.tools.jdbc.DefaultConnection, java.sql.Connection
    public String nativeSQL(String sql) throws SQLException {
        if (log.isDebugEnabled()) {
            log.debug("nativeSQL", sql);
        }
        return super.nativeSQL(sql);
    }
}
