package org.jooq.tools.jdbc;

import java.io.InputStream;
import java.io.Reader;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.Date;
import java.sql.NClob;
import java.sql.ParameterMetaData;
import java.sql.Ref;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import org.jooq.Record;

/* loaded from: server.jar:BOOT-INF/lib/jooq-3.19.3.jar:org/jooq/tools/jdbc/MockStatement.class */
public class MockStatement extends JDBC41Statement implements CallableStatement {
    private final MockConnection connection;
    private final MockDataProvider data;
    private final List<String> sql;
    private final List<List<Object>> bindings;
    private final List<Integer> outParameterTypes;
    private MockResult[] result;
    private int resultIndex;
    private boolean resultWasNull;
    private boolean isClosed;
    int resultSetType;
    int resultSetConcurrency;
    int resultSetHoldability;
    int autoGeneratedKeys;
    int[] columnIndexes;
    String[] columnNames;
    MockExecuteContext context;
    private int queryTimeout;
    private int maxRows;

    public MockStatement(MockConnection connection, MockDataProvider data) {
        this(connection, data, null);
    }

    public MockStatement(MockConnection connection, MockDataProvider data, String sql) {
        this.resultSetType = 1003;
        this.resultSetConcurrency = 1007;
        this.resultSetHoldability = 2;
        this.autoGeneratedKeys = 2;
        this.connection = connection;
        this.data = data;
        this.sql = new ArrayList();
        this.bindings = new ArrayList();
        this.outParameterTypes = new ArrayList();
        if (sql != null) {
            this.sql.add(sql);
        }
        this.bindings.add(new ArrayList());
    }

    private List<Object> bindings() {
        return this.bindings.get(this.bindings.size() - 1);
    }

    private void ensureBindingsCapacity(int index) {
        List<Object> b = bindings();
        if (b.size() < index) {
            b.addAll(Collections.nCopies(index - b.size(), null));
        }
    }

    private void ensureOutParameterTypesCapacity(int index) {
        if (this.outParameterTypes.size() < index) {
            this.outParameterTypes.addAll(Collections.nCopies(index - this.outParameterTypes.size(), (Integer) null));
        }
    }

    private void checkNotClosed() throws SQLException {
        if (this.isClosed) {
            throw new SQLException("Connection is already closed");
        }
    }

    private boolean checkException() throws SQLException {
        if (this.result[this.resultIndex].exception != null) {
            throw this.result[this.resultIndex].exception;
        }
        return true;
    }

    @Override // java.sql.Statement
    public Connection getConnection() throws SQLException {
        return this.connection;
    }

    /* JADX WARN: Type inference failed for: r4v2, types: [java.lang.Object[], java.lang.Object[][]] */
    private boolean execute0(String localSql, int localResultSetType, int localResultSetConcurrency, int localResultSetHoldability, int localAutoGeneratedKeys, int[] localColumnIndexes, String[] localColumnNames) throws SQLException {
        checkNotClosed();
        this.context = new MockExecuteContext(new String[]{localSql}, new Object[]{bindings().toArray()}, localAutoGeneratedKeys, localColumnIndexes, localColumnNames, unbox(this.outParameterTypes));
        this.result = this.data.execute(this.context);
        if (!this.outParameterTypes.isEmpty()) {
            this.resultIndex++;
        }
        return this.result != null && this.result.length > this.resultIndex && checkException() && this.result[this.resultIndex].data != null && (this.resultIndex > 0 || localAutoGeneratedKeys == 2);
    }

    private static final int[] unbox(List<Integer> list) {
        int[] array = new int[list.size()];
        for (int i = 0; i < array.length; i++) {
            Integer value = list.get(i);
            array[i] = value == null ? 0 : value.intValue();
        }
        return array;
    }

    @Override // java.sql.Statement
    public ResultSet getGeneratedKeys() throws SQLException {
        return getResultSet();
    }

    @Override // java.sql.Statement
    public boolean getMoreResults() throws SQLException {
        return getMoreResults(1);
    }

    @Override // java.sql.Statement
    public boolean getMoreResults(int current) throws SQLException {
        if (this.result != null) {
            int i = this.resultIndex + 1;
            this.resultIndex = i;
            if (i < this.result.length && checkException()) {
                return true;
            }
        }
        return false;
    }

    @Override // java.sql.Statement
    public ResultSet getResultSet() throws SQLException {
        checkNotClosed();
        if (this.result != null && this.resultIndex < this.result.length && this.result[this.resultIndex].data != null) {
            return new MockResultSet(this.result[this.resultIndex].data, this.maxRows);
        }
        return null;
    }

    @Override // java.sql.Statement
    public int getUpdateCount() throws SQLException {
        checkNotClosed();
        if (this.result != null && this.resultIndex < this.result.length && (this.result[this.resultIndex].data == null || (this.resultIndex == 0 && this.context.autoGeneratedKeys() == 1))) {
            return this.result[this.resultIndex].rows;
        }
        return -1;
    }

    @Override // java.sql.PreparedStatement
    public ResultSet executeQuery() throws SQLException {
        return executeQuery(this.sql.get(0));
    }

    @Override // java.sql.Statement
    public ResultSet executeQuery(String localSql) throws SQLException {
        execute0(localSql, this.resultSetType, this.resultSetConcurrency, this.resultSetHoldability, this.autoGeneratedKeys, this.columnIndexes, this.columnNames);
        return getResultSet();
    }

    @Override // java.sql.PreparedStatement
    public boolean execute() throws SQLException {
        return execute(this.sql.get(0));
    }

    @Override // java.sql.Statement
    public boolean execute(String localSql) throws SQLException {
        return execute0(localSql, this.resultSetType, this.resultSetConcurrency, this.resultSetHoldability, this.autoGeneratedKeys, this.columnIndexes, this.columnNames);
    }

    @Override // java.sql.Statement
    public boolean execute(String localSql, int localAutoGeneratedKeys) throws SQLException {
        return execute0(localSql, this.resultSetType, this.resultSetConcurrency, this.resultSetHoldability, localAutoGeneratedKeys, null, null);
    }

    @Override // java.sql.Statement
    public boolean execute(String localSql, int[] localColumnIndexes) throws SQLException {
        return execute0(localSql, this.resultSetType, this.resultSetConcurrency, this.resultSetHoldability, 1, localColumnIndexes, null);
    }

    @Override // java.sql.Statement
    public boolean execute(String localSql, String[] localColumnNames) throws SQLException {
        return execute0(localSql, this.resultSetType, this.resultSetConcurrency, this.resultSetHoldability, 1, null, localColumnNames);
    }

    @Override // java.sql.PreparedStatement
    public int executeUpdate() throws SQLException {
        return executeUpdate(this.sql.get(0));
    }

    @Override // java.sql.Statement
    public int executeUpdate(String localSql) throws SQLException {
        execute0(localSql, this.resultSetType, this.resultSetConcurrency, this.resultSetHoldability, this.autoGeneratedKeys, this.columnIndexes, this.columnNames);
        return getUpdateCount();
    }

    @Override // java.sql.Statement
    public int executeUpdate(String localSql, int localAutoGeneratedKeys) throws SQLException {
        execute0(localSql, this.resultSetType, this.resultSetConcurrency, this.resultSetHoldability, localAutoGeneratedKeys, null, null);
        return getUpdateCount();
    }

    @Override // java.sql.Statement
    public int executeUpdate(String localSql, int[] localColumnIndexes) throws SQLException {
        execute0(localSql, this.resultSetType, this.resultSetConcurrency, this.resultSetHoldability, 1, localColumnIndexes, null);
        return getUpdateCount();
    }

    @Override // java.sql.Statement
    public int executeUpdate(String localSql, String[] localColumnNames) throws SQLException {
        execute0(localSql, this.resultSetType, this.resultSetConcurrency, this.resultSetHoldability, 1, null, localColumnNames);
        return getUpdateCount();
    }

    @Override // java.sql.PreparedStatement
    public void addBatch() throws SQLException {
        checkNotClosed();
        this.bindings.add(new ArrayList());
    }

    @Override // java.sql.Statement
    public void addBatch(String localSql) throws SQLException {
        checkNotClosed();
        this.sql.add(localSql);
    }

    @Override // java.sql.Statement
    public void clearBatch() throws SQLException {
        checkNotClosed();
        this.sql.clear();
        this.bindings.clear();
        this.bindings.add(new ArrayList());
    }

    /* JADX WARN: Type inference failed for: r0v5, types: [java.lang.Object[], java.lang.Object[][]] */
    @Override // java.sql.Statement
    public int[] executeBatch() throws SQLException {
        checkNotClosed();
        ?? r0 = new Object[this.bindings.size() - 1];
        for (int i = 0; i < this.bindings.size() - 1; i++) {
            r0[i] = this.bindings.get(i).toArray();
        }
        this.result = this.data.execute(new MockExecuteContext((String[]) this.sql.toArray(new String[0]), r0));
        int[] rows = new int[this.result.length];
        for (int i2 = 0; i2 < this.result.length; i2++) {
            rows[i2] = this.result[i2].rows;
        }
        return rows;
    }

    @Override // java.sql.PreparedStatement
    public void clearParameters() throws SQLException {
        checkNotClosed();
        List<Object> b = bindings();
        for (int i = 0; i < b.size(); i++) {
            b.set(i, null);
        }
    }

    @Override // java.sql.PreparedStatement
    public void setNull(int parameterIndex, int sqlType) throws SQLException {
        checkNotClosed();
        ensureBindingsCapacity(parameterIndex);
        bindings().set(parameterIndex - 1, null);
    }

    @Override // java.sql.PreparedStatement
    public void setNull(int parameterIndex, int sqlType, String typeName) throws SQLException {
        checkNotClosed();
        ensureBindingsCapacity(parameterIndex);
        bindings().set(parameterIndex - 1, null);
    }

    @Override // java.sql.PreparedStatement
    public void setBoolean(int parameterIndex, boolean x) throws SQLException {
        checkNotClosed();
        ensureBindingsCapacity(parameterIndex);
        bindings().set(parameterIndex - 1, Boolean.valueOf(x));
    }

    @Override // java.sql.PreparedStatement
    public void setByte(int parameterIndex, byte x) throws SQLException {
        checkNotClosed();
        ensureBindingsCapacity(parameterIndex);
        bindings().set(parameterIndex - 1, Byte.valueOf(x));
    }

    @Override // java.sql.PreparedStatement
    public void setShort(int parameterIndex, short x) throws SQLException {
        checkNotClosed();
        ensureBindingsCapacity(parameterIndex);
        bindings().set(parameterIndex - 1, Short.valueOf(x));
    }

    @Override // java.sql.PreparedStatement
    public void setInt(int parameterIndex, int x) throws SQLException {
        checkNotClosed();
        ensureBindingsCapacity(parameterIndex);
        bindings().set(parameterIndex - 1, Integer.valueOf(x));
    }

    @Override // java.sql.PreparedStatement
    public void setLong(int parameterIndex, long x) throws SQLException {
        checkNotClosed();
        ensureBindingsCapacity(parameterIndex);
        bindings().set(parameterIndex - 1, Long.valueOf(x));
    }

    @Override // java.sql.PreparedStatement
    public void setFloat(int parameterIndex, float x) throws SQLException {
        checkNotClosed();
        ensureBindingsCapacity(parameterIndex);
        bindings().set(parameterIndex - 1, Float.valueOf(x));
    }

    @Override // java.sql.PreparedStatement
    public void setDouble(int parameterIndex, double x) throws SQLException {
        checkNotClosed();
        ensureBindingsCapacity(parameterIndex);
        bindings().set(parameterIndex - 1, Double.valueOf(x));
    }

    @Override // java.sql.PreparedStatement
    public void setBigDecimal(int parameterIndex, BigDecimal x) throws SQLException {
        checkNotClosed();
        ensureBindingsCapacity(parameterIndex);
        bindings().set(parameterIndex - 1, x);
    }

    @Override // java.sql.PreparedStatement
    public void setString(int parameterIndex, String x) throws SQLException {
        checkNotClosed();
        ensureBindingsCapacity(parameterIndex);
        bindings().set(parameterIndex - 1, x);
    }

    @Override // java.sql.PreparedStatement
    public void setNString(int parameterIndex, String value) throws SQLException {
        ensureBindingsCapacity(parameterIndex);
        bindings().set(parameterIndex - 1, value);
    }

    @Override // java.sql.PreparedStatement
    public void setBytes(int parameterIndex, byte[] x) throws SQLException {
        checkNotClosed();
        ensureBindingsCapacity(parameterIndex);
        bindings().set(parameterIndex - 1, x);
    }

    @Override // java.sql.PreparedStatement
    public void setDate(int parameterIndex, Date x) throws SQLException {
        checkNotClosed();
        ensureBindingsCapacity(parameterIndex);
        bindings().set(parameterIndex - 1, x);
    }

    @Override // java.sql.PreparedStatement
    public void setTime(int parameterIndex, Time x) throws SQLException {
        checkNotClosed();
        ensureBindingsCapacity(parameterIndex);
        bindings().set(parameterIndex - 1, x);
    }

    @Override // java.sql.PreparedStatement
    public void setTimestamp(int parameterIndex, Timestamp x) throws SQLException {
        checkNotClosed();
        ensureBindingsCapacity(parameterIndex);
        bindings().set(parameterIndex - 1, x);
    }

    @Override // java.sql.PreparedStatement
    public void setObject(int parameterIndex, Object x, int targetSqlType) throws SQLException {
        checkNotClosed();
        ensureBindingsCapacity(parameterIndex);
        bindings().set(parameterIndex - 1, x);
    }

    @Override // java.sql.PreparedStatement
    public void setObject(int parameterIndex, Object x) throws SQLException {
        checkNotClosed();
        ensureBindingsCapacity(parameterIndex);
        bindings().set(parameterIndex - 1, x);
    }

    @Override // java.sql.PreparedStatement
    public void setObject(int parameterIndex, Object x, int targetSqlType, int scaleOrLength) throws SQLException {
        checkNotClosed();
        ensureBindingsCapacity(parameterIndex);
        bindings().set(parameterIndex - 1, x);
    }

    @Override // java.sql.PreparedStatement
    public void setURL(int parameterIndex, URL x) throws SQLException {
        checkNotClosed();
        ensureBindingsCapacity(parameterIndex);
        bindings().set(parameterIndex - 1, x);
    }

    @Override // java.sql.PreparedStatement
    public void setArray(int parameterIndex, Array x) throws SQLException {
        checkNotClosed();
        ensureBindingsCapacity(parameterIndex);
        bindings().set(parameterIndex - 1, x.getArray());
    }

    private Record outParameters() throws SQLException {
        if (this.result == null || this.result.length == 0 || this.result[0].data == null || this.result[0].data.size() == 0) {
            throw new SQLException("No OUT Parameters available");
        }
        return (Record) this.result[0].data.get(0);
    }

    private int translate(int parameterIndex) throws SQLException {
        if (parameterIndex > this.outParameterTypes.size()) {
            throw new SQLException("OUT parameter index too high: " + parameterIndex);
        }
        int index = -1;
        for (int i = 0; i < parameterIndex; i++) {
            if (this.outParameterTypes.get(i) != null) {
                index++;
            }
        }
        return index;
    }

    @Override // java.sql.CallableStatement
    public void registerOutParameter(int parameterIndex, int sqlType) throws SQLException {
        checkNotClosed();
        ensureBindingsCapacity(parameterIndex);
        ensureOutParameterTypesCapacity(parameterIndex);
        this.outParameterTypes.set(parameterIndex - 1, Integer.valueOf(sqlType));
    }

    @Override // java.sql.CallableStatement
    public void registerOutParameter(int parameterIndex, int sqlType, int scale) throws SQLException {
        registerOutParameter(parameterIndex, sqlType);
    }

    @Override // java.sql.CallableStatement
    public void registerOutParameter(int parameterIndex, int sqlType, String typeName) throws SQLException {
        registerOutParameter(parameterIndex, sqlType);
    }

    @Override // java.sql.CallableStatement
    public boolean wasNull() throws SQLException {
        return this.resultWasNull;
    }

    @Override // java.sql.CallableStatement
    public String getString(int parameterIndex) throws SQLException {
        String value = (String) outParameters().get(translate(parameterIndex), String.class);
        this.resultWasNull = value == null;
        return value;
    }

    @Override // java.sql.CallableStatement
    public String getNString(int parameterIndex) throws SQLException {
        String value = (String) outParameters().get(translate(parameterIndex), String.class);
        this.resultWasNull = value == null;
        return value;
    }

    @Override // java.sql.CallableStatement
    public boolean getBoolean(int parameterIndex) throws SQLException {
        Boolean value = (Boolean) outParameters().get(translate(parameterIndex), Boolean.class);
        this.resultWasNull = value == null;
        if (value == null) {
            return false;
        }
        return value.booleanValue();
    }

    @Override // java.sql.CallableStatement
    public byte getByte(int parameterIndex) throws SQLException {
        Byte value = (Byte) outParameters().get(translate(parameterIndex), Byte.class);
        this.resultWasNull = value == null;
        if (value == null) {
            return (byte) 0;
        }
        return value.byteValue();
    }

    @Override // java.sql.CallableStatement
    public short getShort(int parameterIndex) throws SQLException {
        Short value = (Short) outParameters().get(translate(parameterIndex), Short.class);
        this.resultWasNull = value == null;
        if (value == null) {
            return (short) 0;
        }
        return value.shortValue();
    }

    @Override // java.sql.CallableStatement
    public int getInt(int parameterIndex) throws SQLException {
        Integer value = (Integer) outParameters().get(translate(parameterIndex), Integer.class);
        this.resultWasNull = value == null;
        if (value == null) {
            return 0;
        }
        return value.intValue();
    }

    @Override // java.sql.CallableStatement
    public long getLong(int parameterIndex) throws SQLException {
        Long value = (Long) outParameters().get(translate(parameterIndex), Long.class);
        this.resultWasNull = value == null;
        if (value == null) {
            return 0L;
        }
        return value.longValue();
    }

    @Override // java.sql.CallableStatement
    public float getFloat(int parameterIndex) throws SQLException {
        Float value = (Float) outParameters().get(translate(parameterIndex), Float.class);
        this.resultWasNull = value == null;
        if (value == null) {
            return 0.0f;
        }
        return value.floatValue();
    }

    @Override // java.sql.CallableStatement
    public double getDouble(int parameterIndex) throws SQLException {
        Double value = (Double) outParameters().get(translate(parameterIndex), Double.class);
        this.resultWasNull = value == null;
        if (value == null) {
            return 0.0d;
        }
        return value.doubleValue();
    }

    @Override // java.sql.CallableStatement
    public BigDecimal getBigDecimal(int parameterIndex, int scale) throws SQLException {
        BigDecimal value = (BigDecimal) outParameters().get(translate(parameterIndex), BigDecimal.class);
        this.resultWasNull = value == null;
        return value;
    }

    @Override // java.sql.CallableStatement
    public BigDecimal getBigDecimal(int parameterIndex) throws SQLException {
        BigDecimal value = (BigDecimal) outParameters().get(translate(parameterIndex), BigDecimal.class);
        this.resultWasNull = value == null;
        return value;
    }

    @Override // java.sql.CallableStatement
    public byte[] getBytes(int parameterIndex) throws SQLException {
        byte[] value = (byte[]) outParameters().get(translate(parameterIndex), byte[].class);
        this.resultWasNull = value == null;
        return value;
    }

    @Override // java.sql.CallableStatement
    public Date getDate(int parameterIndex) throws SQLException {
        Date value = (Date) outParameters().get(translate(parameterIndex), Date.class);
        this.resultWasNull = value == null;
        return value;
    }

    @Override // java.sql.CallableStatement
    public Date getDate(int parameterIndex, Calendar cal) throws SQLException {
        Date value = (Date) outParameters().get(translate(parameterIndex), Date.class);
        this.resultWasNull = value == null;
        return value;
    }

    @Override // java.sql.CallableStatement
    public Time getTime(int parameterIndex) throws SQLException {
        Time value = (Time) outParameters().get(translate(parameterIndex), Time.class);
        this.resultWasNull = value == null;
        return value;
    }

    @Override // java.sql.CallableStatement
    public Time getTime(int parameterIndex, Calendar cal) throws SQLException {
        Time value = (Time) outParameters().get(translate(parameterIndex), Time.class);
        this.resultWasNull = value == null;
        return value;
    }

    @Override // java.sql.CallableStatement
    public Timestamp getTimestamp(int parameterIndex) throws SQLException {
        Timestamp value = (Timestamp) outParameters().get(translate(parameterIndex), Timestamp.class);
        this.resultWasNull = value == null;
        return value;
    }

    @Override // java.sql.CallableStatement
    public Timestamp getTimestamp(int parameterIndex, Calendar cal) throws SQLException {
        Timestamp value = (Timestamp) outParameters().get(translate(parameterIndex), Timestamp.class);
        this.resultWasNull = value == null;
        return value;
    }

    @Override // java.sql.CallableStatement
    public Object getObject(int parameterIndex) throws SQLException {
        Object value = outParameters().get(translate(parameterIndex));
        this.resultWasNull = value == null;
        return value;
    }

    @Override // java.sql.CallableStatement
    public Object getObject(int parameterIndex, Map<String, Class<?>> map) throws SQLException {
        Object value = outParameters().get(translate(parameterIndex));
        this.resultWasNull = value == null;
        return value;
    }

    @Override // java.sql.CallableStatement
    public Array getArray(int parameterIndex) throws SQLException {
        Array value = (Array) outParameters().get(translate(parameterIndex), Array.class);
        this.resultWasNull = value == null;
        return value;
    }

    @Override // java.sql.CallableStatement
    public URL getURL(int parameterIndex) throws SQLException {
        URL value = (URL) outParameters().get(translate(parameterIndex), URL.class);
        this.resultWasNull = value == null;
        return value;
    }

    @Override // java.sql.Statement
    public boolean isClosed() throws SQLException {
        return this.isClosed;
    }

    @Override // java.sql.Statement, java.lang.AutoCloseable
    public void close() throws SQLException {
        this.isClosed = true;
    }

    @Override // java.sql.Statement
    public void cancel() throws SQLException {
        this.isClosed = true;
    }

    @Override // java.sql.Statement
    public int getMaxFieldSize() throws SQLException {
        checkNotClosed();
        return 0;
    }

    @Override // java.sql.Statement
    public void setMaxFieldSize(int max) throws SQLException {
        checkNotClosed();
    }

    @Override // java.sql.Statement
    public int getMaxRows() throws SQLException {
        checkNotClosed();
        return this.maxRows;
    }

    @Override // java.sql.Statement
    public void setMaxRows(int max) throws SQLException {
        checkNotClosed();
        this.maxRows = max;
    }

    @Override // java.sql.Statement
    public void setEscapeProcessing(boolean enable) throws SQLException {
        checkNotClosed();
    }

    @Override // java.sql.Statement
    public int getQueryTimeout() throws SQLException {
        checkNotClosed();
        return this.queryTimeout;
    }

    @Override // java.sql.Statement
    public void setQueryTimeout(int seconds) throws SQLException {
        checkNotClosed();
        this.queryTimeout = seconds;
    }

    @Override // java.sql.Statement
    public void setFetchDirection(int direction) throws SQLException {
        checkNotClosed();
    }

    @Override // java.sql.Statement
    public int getFetchDirection() throws SQLException {
        checkNotClosed();
        return 0;
    }

    @Override // java.sql.Statement
    public void setFetchSize(int rows) throws SQLException {
        checkNotClosed();
    }

    @Override // java.sql.Statement
    public int getFetchSize() throws SQLException {
        checkNotClosed();
        return 0;
    }

    @Override // java.sql.Statement
    public int getResultSetConcurrency() throws SQLException {
        checkNotClosed();
        return 0;
    }

    @Override // java.sql.Statement
    public int getResultSetType() throws SQLException {
        checkNotClosed();
        return 0;
    }

    @Override // java.sql.Statement
    public int getResultSetHoldability() throws SQLException {
        checkNotClosed();
        return 0;
    }

    @Override // java.sql.Statement
    public void setPoolable(boolean poolable) throws SQLException {
        checkNotClosed();
    }

    @Override // java.sql.Statement
    public boolean isPoolable() throws SQLException {
        checkNotClosed();
        return false;
    }

    @Override // java.sql.Statement
    public SQLWarning getWarnings() throws SQLException {
        checkNotClosed();
        return null;
    }

    @Override // java.sql.Statement
    public void clearWarnings() throws SQLException {
        checkNotClosed();
    }

    @Override // java.sql.Statement
    public void setCursorName(String name) throws SQLException {
        checkNotClosed();
    }

    @Override // java.sql.PreparedStatement
    public ResultSetMetaData getMetaData() throws SQLException {
        checkNotClosed();
        throw new SQLException("Can this be ignored?");
    }

    /* JADX WARN: Multi-variable type inference failed */
    @Override // java.sql.Wrapper
    public <T> T unwrap(Class<T> iface) throws SQLException {
        if (isWrapperFor(iface)) {
            return this;
        }
        throw new SQLException("MockStatement does not implement " + String.valueOf(iface));
    }

    @Override // java.sql.Wrapper
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        return iface.isInstance(this);
    }

    @Override // java.sql.PreparedStatement
    public ParameterMetaData getParameterMetaData() throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.PreparedStatement
    public void setAsciiStream(int parameterIndex, InputStream x, int length) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.PreparedStatement
    public void setAsciiStream(int parameterIndex, InputStream x, long length) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.PreparedStatement
    public void setAsciiStream(int parameterIndex, InputStream x) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setAsciiStream(String parameterName, InputStream x, long length) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setAsciiStream(String parameterName, InputStream x) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setAsciiStream(String parameterName, InputStream x, int length) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.PreparedStatement
    public void setUnicodeStream(int parameterIndex, InputStream x, int length) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.PreparedStatement
    public void setBinaryStream(int parameterIndex, InputStream x, int length) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.PreparedStatement
    public void setBinaryStream(int parameterIndex, InputStream x, long length) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.PreparedStatement
    public void setBinaryStream(int parameterIndex, InputStream x) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setBinaryStream(String parameterName, InputStream x, long length) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setBinaryStream(String parameterName, InputStream x) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setBinaryStream(String parameterName, InputStream x, int length) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.PreparedStatement
    public void setCharacterStream(int parameterIndex, Reader reader, int length) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.PreparedStatement
    public void setCharacterStream(int parameterIndex, Reader reader, long length) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.PreparedStatement
    public void setCharacterStream(int parameterIndex, Reader reader) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setCharacterStream(String parameterName, Reader reader, long length) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setCharacterStream(String parameterName, Reader reader) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setCharacterStream(String parameterName, Reader reader, int length) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.PreparedStatement
    public void setNCharacterStream(int parameterIndex, Reader value, long length) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.PreparedStatement
    public void setNCharacterStream(int parameterIndex, Reader value) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setNCharacterStream(String parameterName, Reader value) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setNCharacterStream(String parameterName, Reader value, long length) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.PreparedStatement
    public void setRef(int parameterIndex, Ref x) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.PreparedStatement
    public void setBlob(int parameterIndex, Blob x) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.PreparedStatement
    public void setBlob(int parameterIndex, InputStream inputStream, long length) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.PreparedStatement
    public void setBlob(int parameterIndex, InputStream inputStream) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setBlob(String parameterName, Blob x) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setBlob(String parameterName, InputStream inputStream) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setBlob(String parameterName, InputStream inputStream, long length) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.PreparedStatement
    public void setClob(int parameterIndex, Clob x) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.PreparedStatement
    public void setClob(int parameterIndex, Reader reader, long length) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.PreparedStatement
    public void setClob(int parameterIndex, Reader reader) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setClob(String parameterName, Clob x) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setClob(String parameterName, Reader reader) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setClob(String parameterName, Reader reader, long length) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.PreparedStatement
    public void setNClob(int parameterIndex, NClob value) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.PreparedStatement
    public void setNClob(int parameterIndex, Reader reader, long length) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.PreparedStatement
    public void setNClob(int parameterIndex, Reader reader) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setNClob(String parameterName, NClob value) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setNClob(String parameterName, Reader reader, long length) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setNClob(String parameterName, Reader reader) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setNString(String parameterName, String value) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.PreparedStatement
    public void setRowId(int parameterIndex, RowId x) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setRowId(String parameterName, RowId x) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.PreparedStatement
    public void setSQLXML(int parameterIndex, SQLXML xmlObject) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setSQLXML(String parameterName, SQLXML xmlObject) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.PreparedStatement
    public void setDate(int parameterIndex, Date x, Calendar cal) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setDate(String parameterName, Date x) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setDate(String parameterName, Date x, Calendar cal) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.PreparedStatement
    public void setTime(int parameterIndex, Time x, Calendar cal) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setTime(String parameterName, Time x) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setTime(String parameterName, Time x, Calendar cal) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.PreparedStatement
    public void setTimestamp(int parameterIndex, Timestamp x, Calendar cal) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setTimestamp(String parameterName, Timestamp x) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setTimestamp(String parameterName, Timestamp x, Calendar cal) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setURL(String parameterName, URL val) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setNull(String parameterName, int sqlType) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setNull(String parameterName, int sqlType, String typeName) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setBoolean(String parameterName, boolean x) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setByte(String parameterName, byte x) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setShort(String parameterName, short x) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setInt(String parameterName, int x) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setLong(String parameterName, long x) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setFloat(String parameterName, float x) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setDouble(String parameterName, double x) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setBigDecimal(String parameterName, BigDecimal x) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setString(String parameterName, String x) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setBytes(String parameterName, byte[] x) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setObject(String parameterName, Object x, int targetSqlType, int scale) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setObject(String parameterName, Object x, int targetSqlType) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void setObject(String parameterName, Object x) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void registerOutParameter(String parameterName, int sqlType) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void registerOutParameter(String parameterName, int sqlType, int scale) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public void registerOutParameter(String parameterName, int sqlType, String typeName) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public String getString(String parameterName) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public boolean getBoolean(String parameterName) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public byte getByte(String parameterName) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public short getShort(String parameterName) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public int getInt(String parameterName) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public long getLong(String parameterName) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public float getFloat(String parameterName) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public double getDouble(String parameterName) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public byte[] getBytes(String parameterName) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public Date getDate(String parameterName) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public Time getTime(String parameterName) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public Timestamp getTimestamp(String parameterName) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public Object getObject(String parameterName) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public BigDecimal getBigDecimal(String parameterName) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public Object getObject(String parameterName, Map<String, Class<?>> map) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public Ref getRef(int parameterIndex) throws SQLException {
        return null;
    }

    @Override // java.sql.CallableStatement
    public Ref getRef(String parameterName) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public Blob getBlob(int parameterIndex) throws SQLException {
        return null;
    }

    @Override // java.sql.CallableStatement
    public Blob getBlob(String parameterName) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public Clob getClob(int parameterIndex) throws SQLException {
        return null;
    }

    @Override // java.sql.CallableStatement
    public Clob getClob(String parameterName) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public NClob getNClob(int parameterIndex) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public NClob getNClob(String parameterName) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public String getNString(String parameterName) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public Reader getNCharacterStream(int parameterIndex) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public Reader getNCharacterStream(String parameterName) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public Reader getCharacterStream(int parameterIndex) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public Reader getCharacterStream(String parameterName) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public Array getArray(String parameterName) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public Date getDate(String parameterName, Calendar cal) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public Time getTime(String parameterName, Calendar cal) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public Timestamp getTimestamp(String parameterName, Calendar cal) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public URL getURL(String parameterName) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public RowId getRowId(int parameterIndex) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public RowId getRowId(String parameterName) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public SQLXML getSQLXML(int parameterIndex) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }

    @Override // java.sql.CallableStatement
    public SQLXML getSQLXML(String parameterName) throws SQLException {
        throw new SQLFeatureNotSupportedException("Unsupported Operation");
    }
}
